server:
  port: 40080
---
# Admin 配置
spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://127.0.0.1:${server.port}${spring.boot.admin.context-path}
      context-path: /admin-actuator
# Actuator 监控端点的配置项
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
---
# Swagger & 增强配置
knife4j:
  enable: true
  setting:
    enableSwaggerModels: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2022-[夜月](https://gitee.com/fredyangyeyue/ruoyi-study-demo)
swagger:
  enable: true
  title: 夜月后端接口文档
  description: 芋艿若依增强脚手架学习接口文档
  author: 夜月
  version: 1.0.0
---
# 数据源配置
spring:
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username:
        login-password:
    dynamic:
      primary: master
      druid:
        initial-size: 5
        min-idle: 10
        max-active: 20
        max-wait: 600000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis: 900000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        filters: stat,wall,slf4j
        stat:
          db-type: mysql
          merge-sql: true
          log-slow-sql: true
          slow-sql-log-level: WARN
          slow-sql-millis: 100
        wall:
          truncate-allow: false
          multi-statement-allow: true
          drop-table-allow: false
        slf4j:
          statement-executable-sql-log-enable: true
          statement-close-after-log-enabled: false
          statement-create-after-log-enabled: false
          statement-parameter-set-log-enabled: false
          statement-parameter-clear-log-enable: false
          statement-prepare-call-after-log-enabled: false
          statement-prepare-after-log-enabled: false
      datasource:
        master:
          name: ruoyi_study_demo
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.master.name}?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
        quartz:
          name: ruoyi_study_demo_quartz
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.quartz.name}?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
---
# Redis
spring:
  redis:
    password: 123456
    database: 0
---
# Quartz
spring:
  quartz:
    scheduler-name: yeyue-cluster-scheduler
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: false
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: yeyue-cluster-scheduler
            instanceId: AUTO
          jobStore:
            isClustered: true # 是集群模式
            clusterCheckinInterval: 15000 # 集群检查频率，单位：毫秒。默认为 15000，即 15 秒
            misfireThreshold: 60000 # misfire 阀值，单位：毫秒
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
