spring:
  application:
    name: yeyue-ruoyi-server
  profiles:
    active: dev
---
# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
---
# Jackson 配置
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      write-enums-using-to-string: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
---
# 自定义验证码配置
captcha:
  width: 200
  height: 60
  code-count: 5
  interfere-count: 150
  timeout: 5m