server:
  port: 40080
---
spring:
  application:
    name: yeyue-ruoyi-server
---
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      write-enums-using-to-string: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
---
spring:
  redis:
    password: yeyue2019
    database: 0
---
knife4j:
  enable: true
  setting:
    enableSwaggerModels: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2022-[夜月](https://gitee.com/fredyangyeyue/ruoyi-study-demo)
swagger:
  enable: true
  title: 夜月后端接口文档
  description: 芋艿若依增强脚手架学习接口文档
  author: 夜月
  version: 1.0.0

